{
 "title": "Email quota usage",
 "time": { "from": "now-1y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "email",
    "query": "ispconfig.*.monitor_data.email_quota.*"
   }
  ]
 },
 "panels": [
  {
   "title": "Email quota usage (25GB+)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "minimumAbove(aliasByNode(ispconfig.*.monitor_data.email_quota.$email, 4), 26843545600)"
    }
   ]
  },
  {
   "title": "Email quota usage (below 25GB)",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 20, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "maximumBelow(aliasByNode(ispconfig.*.monitor_data.email_quota.$email, 4), 26843545600)"
    }
   ]
  },
  {
   "title": "Email quota usages changes",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 20, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "aliasByNode(derivative(keepLastValue(ispconfig.*.monitor_data.email_quota.$email)), 4)"
    }
   ]
  }
 ]
}